#Written programmetically!
!!python/object:swmmeaproject.parameters_class_
calfile: E:\learn\swmm5ea-repo\swmm5-ea\examples\watershed_calibration\linkt5flow.cal
calid: [0, T5]
caltype:
- 7
- [2, 0]
- Link Flow
cost_function: !!python/unicode 'v1*1000+v2*1000+v3*1000+v4*1000+v5*1000'
crossover_rate: 0.5
gnuplot: gnuplot/pgnuplot.exe
gnuplotdata: data.dat
gnuplotscript: plotfile.plt
max_evaluations: 2400
maximize: false
mutation_rate: 0.2
num_cpus: 4
num_crossover_points: 2
num_elites: 1
num_inputs: 6
num_selected: 12
pop_size: 12
swmmResultCodes: [2, 0, 0]
swmmout_cost_function: !!python/unicode 'f**2.*.1'
swmmouttype: [1, Calibration var.]
valuerange:
- [100.0, 20000.0]
- [0.0001, 5.0]
- [0.0001, 0.5]
- [0.0001, 0.5]
- [1.0, 10.0]
- [1.0, 10.0]
zoomextent: false
