# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\\parameters_dialog_.ui'
#
# Created: Mon Dec 10 19:54:00 2012
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(617, 586)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(300, 540, 291, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(300, 20, 292, 511))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.Cost_function_1 = QtGui.QPlainTextEdit(self.frame_2)
        self.Cost_function_1.setMaximumSize(QtCore.QSize(256, 100))
        self.Cost_function_1.setObjectName(_fromUtf8("Cost_function_1"))
        self.gridLayout_2.addWidget(self.Cost_function_1, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.Cost_function_2 = QtGui.QPlainTextEdit(self.frame_2)
        self.Cost_function_2.setMaximumSize(QtCore.QSize(256, 25))
        self.Cost_function_2.setObjectName(_fromUtf8("Cost_function_2"))
        self.gridLayout_2.addWidget(self.Cost_function_2, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.frame_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 264, 289))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.vlabel1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.vlabel1.setObjectName(_fromUtf8("vlabel1"))
        self.gridLayout_3.addWidget(self.vlabel1, 0, 0, 1, 1)
        self.v_value_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.v_value_2.setObjectName(_fromUtf8("v_value_2"))
        self.gridLayout_3.addWidget(self.v_value_2, 0, 2, 1, 1)
        self.v_value_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.v_value_1.setObjectName(_fromUtf8("v_value_1"))
        self.gridLayout_3.addWidget(self.v_value_1, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.copyButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.copyButton.setMinimumSize(QtCore.QSize(0, 25))
        self.copyButton.setMaximumSize(QtCore.QSize(16777215, 25))
        self.copyButton.setObjectName(_fromUtf8("copyButton"))
        self.gridLayout_4.addWidget(self.copyButton, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 5, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 21, 271, 511))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pop_size = QtGui.QSpinBox(self.frame)
        self.pop_size.setObjectName(_fromUtf8("pop_size"))
        self.gridLayout.addWidget(self.pop_size, 5, 1, 1, 1)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 10, 0, 1, 2)
        self.num_inputs = QtGui.QSpinBox(self.frame)
        self.num_inputs.setMinimum(1)
        self.num_inputs.setProperty(_fromUtf8("value"), 5)
        self.num_inputs.setObjectName(_fromUtf8("num_inputs"))
        self.gridLayout.addWidget(self.num_inputs, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.Number_of_cpus = QtGui.QSpinBox(self.frame)
        self.Number_of_cpus.setMinimum(1)
        self.Number_of_cpus.setMaximum(128)
        self.Number_of_cpus.setObjectName(_fromUtf8("Number_of_cpus"))
        self.gridLayout.addWidget(self.Number_of_cpus, 14, 1, 1, 1)
        self.minimize_button = QtGui.QRadioButton(self.frame)
        self.minimize_button.setChecked(True)
        self.minimize_button.setObjectName(_fromUtf8("minimize_button"))
        self.gridLayout.addWidget(self.minimize_button, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 14, 0, 1, 1)
        self.mutation_rate = QtGui.QDoubleSpinBox(self.frame)
        self.mutation_rate.setDecimals(3)
        self.mutation_rate.setMaximum(1.0)
        self.mutation_rate.setSingleStep(0.01)
        self.mutation_rate.setProperty(_fromUtf8("value"), 0.1)
        self.mutation_rate.setObjectName(_fromUtf8("mutation_rate"))
        self.gridLayout.addWidget(self.mutation_rate, 9, 1, 1, 1)
        self.Crossover_rate = QtGui.QDoubleSpinBox(self.frame)
        self.Crossover_rate.setDecimals(3)
        self.Crossover_rate.setMaximum(1.0)
        self.Crossover_rate.setSingleStep(0.01)
        self.Crossover_rate.setProperty(_fromUtf8("value"), 0.8)
        self.Crossover_rate.setObjectName(_fromUtf8("Crossover_rate"))
        self.gridLayout.addWidget(self.Crossover_rate, 8, 1, 1, 1)
        self.num_evaluations = QtGui.QLineEdit(self.frame)
        self.num_evaluations.setMaxLength(10)
        self.num_evaluations.setObjectName(_fromUtf8("num_evaluations"))
        self.gridLayout.addWidget(self.num_evaluations, 12, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 12, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 13, 0, 1, 2)
        self.num_elites = QtGui.QSpinBox(self.frame)
        self.num_elites.setObjectName(_fromUtf8("num_elites"))
        self.gridLayout.addWidget(self.num_elites, 6, 1, 1, 1)
        self.maximize = QtGui.QRadioButton(self.frame)
        self.maximize.setObjectName(_fromUtf8("maximize"))
        self.gridLayout.addWidget(self.maximize, 1, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.swmmp_1 = QtGui.QSpinBox(self.frame)
        self.swmmp_1.setProperty(_fromUtf8("value"), 3)
        self.swmmp_1.setObjectName(_fromUtf8("swmmp_1"))
        self.gridLayout_8.addWidget(self.swmmp_1, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 2, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.swmmp_2 = QtGui.QSpinBox(self.frame)
        self.swmmp_2.setObjectName(_fromUtf8("swmmp_2"))
        self.gridLayout_9.addWidget(self.swmmp_2, 0, 0, 1, 1)
        self.swmmp_3 = QtGui.QSpinBox(self.frame)
        self.swmmp_3.setProperty(_fromUtf8("value"), 10)
        self.swmmp_3.setObjectName(_fromUtf8("swmmp_3"))
        self.gridLayout_9.addWidget(self.swmmp_3, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_9, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.label_9.setBuddy(self.Cost_function_1)
        self.label_10.setBuddy(self.Cost_function_2)
        self.label_11.setBuddy(self.scrollArea)
        self.label.setBuddy(self.num_inputs)
        self.label_3.setBuddy(self.num_elites)
        self.label_6.setBuddy(self.Crossover_rate)
        self.label_8.setBuddy(self.Number_of_cpus)
        self.label_7.setBuddy(self.mutation_rate)
        self.label_2.setBuddy(self.pop_size)
        self.label_5.setBuddy(self.num_evaluations)
        self.label_4.setBuddy(self.swmmp_1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.num_inputs, self.maximize)
        Dialog.setTabOrder(self.maximize, self.minimize_button)
        Dialog.setTabOrder(self.minimize_button, self.swmmp_1)
        Dialog.setTabOrder(self.swmmp_1, self.swmmp_2)
        Dialog.setTabOrder(self.swmmp_2, self.swmmp_3)
        Dialog.setTabOrder(self.swmmp_3, self.pop_size)
        Dialog.setTabOrder(self.pop_size, self.num_elites)
        Dialog.setTabOrder(self.num_elites, self.Crossover_rate)
        Dialog.setTabOrder(self.Crossover_rate, self.mutation_rate)
        Dialog.setTabOrder(self.mutation_rate, self.num_evaluations)
        Dialog.setTabOrder(self.num_evaluations, self.Number_of_cpus)
        Dialog.setTabOrder(self.Number_of_cpus, self.Cost_function_1)
        Dialog.setTabOrder(self.Cost_function_1, self.Cost_function_2)
        Dialog.setTabOrder(self.Cost_function_2, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.copyButton)
        Dialog.setTabOrder(self.copyButton, self.v_value_1)
        Dialog.setTabOrder(self.v_value_1, self.v_value_2)
        Dialog.setTabOrder(self.v_value_2, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Cos&t Function 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Cos&t Function 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "&Value Ranges", None, QtGui.QApplication.UnicodeUTF8))
        self.vlabel1.setText(QtGui.QApplication.translate("Dialog", "v1", None, QtGui.QApplication.UnicodeUTF8))
        self.v_value_2.setText(QtGui.QApplication.translate("Dialog", "2500.00", None, QtGui.QApplication.UnicodeUTF8))
        self.v_value_1.setText(QtGui.QApplication.translate("Dialog", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.copyButton.setText(QtGui.QApplication.translate("Dialog", "&Copy  v1  to the rest", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "&Number of Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Number of &Elites", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "&Crossover Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.minimize_button.setText(QtGui.QApplication.translate("Dialog", "Minimize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Number of C&PUs", None, QtGui.QApplication.UnicodeUTF8))
        self.num_evaluations.setText(QtGui.QApplication.translate("Dialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "M&utation Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "&Population Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Number of &Evaluations", None, QtGui.QApplication.UnicodeUTF8))
        self.maximize.setText(QtGui.QApplication.translate("Dialog", "&Maximize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "SWM&M Param", None, QtGui.QApplication.UnicodeUTF8))

